name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. If another 60 days pass with no activity, this issue will close.'
          days-before-stale: 60
          days-before-close: 60
          days-before-pr-close: -1
          days-before-pr-stale: -1
          exempt-issue-labels: 📦 Product Roadmap Master Issue
